/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {};
declare global {
  const IconBiMusicNoteList: typeof import('~icons/bi/music-note-list.jsx')['default'];
  const IconBiSliders: typeof import('~icons/bi/sliders.jsx')['default'];
  const IconClarityLightningSolid: typeof import('~icons/clarity/lightning-solid.jsx')['default'];
  const IconCodiconClearAll: typeof import('~icons/codicon/clear-all.jsx')['default'];
  const IconFaSolidFilter: typeof import('~icons/fa-solid/filter.jsx')['default'];
  const IconGgUserlane: typeof import('~icons/gg/userlane.jsx')['default'];
  const IconIonArrowBack: typeof import('~icons/ion/arrow-back.jsx')['default'];
  const IconIonArrowRightC: typeof import('~icons/ion/arrow-right-c.jsx')['default'];
  const IconIonIosMore: typeof import('~icons/ion/ios-more.jsx')['default'];
  const IconIonIosSearch: typeof import('~icons/ion/ios-search.jsx')['default'];
  const IconIonMusicNote: typeof import('~icons/ion/music-note.jsx')['default'];
  const IconIonPerson: typeof import('~icons/ion/person.jsx')['default'];
  const IconIonPlus: typeof import('~icons/ion/plus.jsx')['default'];
  const IconIonSearch: typeof import('~icons/ion/search.jsx')['default'];
  const IconIonSettingsOutline: typeof import('~icons/ion/settings-outline.jsx')['default'];
  const IconLogosDiscordIcon: typeof import('~icons/logos/discord-icon.jsx')['default'];
  const IconLogosGoogleIcon: typeof import('~icons/logos/google-icon.jsx')['default'];
  const IconLogosYoutube: typeof import('~icons/logos/youtube.jsx')['default'];
  const IconLogosYoutubeIcon: typeof import('~icons/logos/youtube-icon.jsx')['default'];
  const IconMdiBlock: typeof import('~icons/mdi/block.jsx')['default'];
  const IconMdiYoutube: typeof import('~icons/mdi/youtube.jsx')['default'];
  const IconMsOpenInNew: typeof import('~icons/material-symbols/open-in-new.jsx')['default'];
  const IconMsScheduleOutlineRounded: typeof import(
    '~icons/material-symbols/schedule-outline-rounded.jsx',
  )['default'];
  const IconRiKakaoTalkFill: typeof import('~icons/ri/kakao-talk-fill.jsx')['default'];
  const IconRiPerson: typeof import('~icons/ri/person.jsx')['default'];
  const IconRxPerson: typeof import('~icons/radix-icons/person.jsx')['default'];
  const IconRxPinTop: typeof import('~icons/radix-icons/pin-top.jsx')['default'];
  const IconSpinner180Ring: typeof import('~icons/svg-spinners/180-ring.jsx')['default'];
  const IconTbCirclePlus: typeof import('~icons/tabler/circle-plus.jsx')['default'];
  const IconTbArrowNarrowLeft: typeof import('~icons/tabler/arrow-narrow-left.jsx')['default'];
  const IconTbArrowNarrowRight: typeof import('~icons/tabler/arrow-narrow-right.jsx')['default'];
  const IconTbArrowRight: typeof import('~icons/tabler/arrow-right.jsx')['default'];
  const IconTbBellRingingFilled: typeof import('~icons/tabler/bell-ringing-filled.jsx')['default'];
  const IconTbBoradcast: typeof import('~icons/tabler/boradcast.jsx')['default'];
  const IconTbBoxMultiple4: typeof import('~icons/tabler/box-multiple4.jsx')['default'];
  const IconTbBroadcast: typeof import('~icons/tabler/broadcast.jsx')['default'];
  const IconTbCheck: typeof import('~icons/tabler/check.jsx')['default'];
  const IconTbChevronLeft: typeof import('~icons/tabler/chevron-left.jsx')['default'];
  const IconTbChevronRight: typeof import('~icons/tabler/chevron-right.jsx')['default'];
  const IconTbCircleArrowUp: typeof import('~icons/tabler/circle-arrow-up.jsx')['default'];
  const IconTbCirclePlus: typeof import('~icons/tabler/circle-plus.jsx')['default'];
  const IconTbClipboard: typeof import('~icons/tabler/clipboard.jsx')['default'];
  const IconTbCopy: typeof import('~icons/tabler/copy.jsx')['default'];
  const IconTbDeviceDesktopCode: typeof import('~icons/tabler/device-desktop-code.jsx')['default'];
  const IconTbDots: typeof import('~icons/tabler/dots.jsx')['default'];
  const IconTbGripVertical: typeof import('~icons/tabler/grip-vertical.jsx')['default'];
  const IconTbHome: typeof import('~icons/tabler/home.jsx')['default'];
  const IconTbList: typeof import('~icons/tabler/list.jsx')['default'];
  const IconTbMicrophone2: typeof import('~icons/tabler/microphone2.jsx')['default'];
  const IconTbNoCopyright: typeof import('~icons/tabler/no-copyright.jsx')['default'];
  const IconTbPlus: typeof import('~icons/tabler/plus.jsx')['default'];
  const IconTbSearch: typeof import('~icons/tabler/search.jsx')['default'];
  const IconTbSetting: typeof import('~icons/tabler/setting.jsx')['default'];
  const IconTbSettings: typeof import('~icons/tabler/settings.jsx')['default'];
  const IconTbStar: typeof import('~icons/tabler/star.jsx')['default'];
  const IconTbStarFilled: typeof import('~icons/tabler/star-filled.jsx')['default'];
  const IconTbStarOutline: typeof import('~icons/tabler/star-outline.jsx')['default'];
  const IconTbTableRow: typeof import('~icons/tabler/table-row.jsx')['default'];
  const IconTbTools: typeof import('~icons/tabler/tools.jsx')['default'];
  const IconTbX: typeof import('~icons/tabler/x.jsx')['default'];
}
