/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconClarityLightningSolid: typeof import('~icons/clarity/lightning-solid.jsx')['default']
  const IconGgUserlane: typeof import('~icons/gg/userlane.jsx')['default']
  const IconIonArrowRightC: typeof import('~icons/ion/arrow-right-c.jsx')['default']
  const IconIonIosMore: typeof import('~icons/ion/ios-more.jsx')['default']
  const IconIonIosSearch: typeof import('~icons/ion/ios-search.jsx')['default']
  const IconIonMusicNote: typeof import('~icons/ion/music-note.jsx')['default']
  const IconIonPerson: typeof import('~icons/ion/person.jsx')['default']
  const IconIonPlus: typeof import('~icons/ion/plus.jsx')['default']
  const IconIonSearch: typeof import('~icons/ion/search.jsx')['default']
  const IconMdiBlock: typeof import('~icons/mdi/block.jsx')['default']
  const IconMdiYoutube: typeof import('~icons/mdi/youtube.jsx')['default']
  const IconMsOpenInNew: typeof import('~icons/material-symbols/open-in-new.jsx')['default']
  const IconMsScheduleOutlineRounded: typeof import('~icons/material-symbols/schedule-outline-rounded.jsx')['default']
  const IconRxPinTop: typeof import('~icons/radix-icons/pin-top.jsx')['default']
  const IconTbBellRingingFilled: typeof import('~icons/tabler/bell-ringing-filled.jsx')['default']
  const IconTbCheck: typeof import('~icons/tabler/check.jsx')['default']
  const IconTbChevronLeft: typeof import('~icons/tabler/chevron-left.jsx')['default']
  const IconTbChevronRight: typeof import('~icons/tabler/chevron-right.jsx')['default']
  const IconTbCopy: typeof import('~icons/tabler/copy.jsx')['default']
  const IconTbDeviceDesktopCode: typeof import('~icons/tabler/device-desktop-code.jsx')['default']
  const IconTbHome: typeof import('~icons/tabler/home.jsx')['default']
  const IconTbList: typeof import('~icons/tabler/list.jsx')['default']
  const IconTbNoCopyright: typeof import('~icons/tabler/no-copyright.jsx')['default']
  const IconTbSearch: typeof import('~icons/tabler/search.jsx')['default']
  const IconTbSettings: typeof import('~icons/tabler/settings.jsx')['default']
  const IconTbStar: typeof import('~icons/tabler/star.jsx')['default']
  const IconTbStarFilled: typeof import('~icons/tabler/star-filled.jsx')['default']
  const IconTbTools: typeof import('~icons/tabler/tools.jsx')['default']
  const IconTbX: typeof import('~icons/tabler/x.jsx')['default']
}
