import 'server-only';
// const DATE_FORMAT = `ALTER SESSION SET NLS_DATE_FORMAT="YYYY/MM/DD HH24:MI:SS"`;

export const MEMBER = `
  CREATE TABLE MEMBER (
    EMAIL VARCHAR2(255) PRIMARY KEY NOT NULL,
    PROVIDER VARCHAR2(20) NOT NULL,
    DISABLED CHAR(1) DEFAULT 'N' NOT NULL,
    LV INT DEFAULT 1 NOT NULL,
    CREATE_AT DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LOGIN_AT DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DISCONNECT CHAR(1) DEFAULT 'N' NOT NULL
  )
`;

export const SETLIST = `
  CREATE TABLE SETLIST (
    VIDEO_ID VARCHAR2(50) PRIMARY KEY NOT NULL,
    DESCRIPTION VARCHAR2(6000) NOT NULL,
    MEMBER_EMAIL VARCHAR2(255) NOT NULL,
    CREATE_AT DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_AT DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHANNEL_ID VARCHAR2(50) NOT NULL,
    BROADCAST_AT DATE NOT NULL,
    TITLE VARCHAR2(255) NOT NULL,
    FOREIGN KEY (MEMBER_EMAIL) REFERENCES MEMBER(EMAIL)
  )
`;

export const BLACKLIST = `
  CREATE TABLE BLACKLIST (
    MEMBER_EMAIL VARCHAR2(255) NOT NULL,
    CHANNEL_ID VARCHAR2(50) NOT NULL,
    FOREIGN KEY (MEMBER_EMAIL) REFERENCES MEMBER(EMAIL)
  )
`;

export const WHITELIST = `
  CREATE TABLE WHITELIST (
    MEMBER_EMAIL VARCHAR2(255) NOT NULL,
    CHANNEL_ID VARCHAR2(50) NOT NULL
    FOREIGN KEY (MEMBER_EMAIL) REFERENCES MEMBER(EMAIL)
  )
`;

export const META = `
  CREATE TABLE META (
    KEY VARCHAR2(255) PRIMARY KEY NOT NULL,
    VALUE VARCHAR2(2000) NOT NULL
  )  
`;
