// SELECT T01.*, T02.EMAIL, COUNT(*) OVER() AS maxCount

export type SetlistOrderType = 'CREATE_AT' | 'BROADCAST_AT';

export const GET_SETLIST = `
  SELECT T01.*, T02.EMAIL
  FROM SETLIST T01, MEMBER T02
  WHERE VIDEO_ID = :videoId
    AND T01.MEMBER_ID = T02.ID 
`;

export const GET_MAX_COUNT = `
  SELECT COUNT(*)
  FROM SETLIST T01
  LEFT JOIN BLACKLIST T03 
    ON T01.CHANNEL_ID = T03.CHANNEL_ID AND T03.MEMBER_ID = :memberId
  WHERE T03.CHANNEL_ID IS NULL
`;

export const GET_ALL_SETLIST = (orderType: SetlistOrderType) => `
  SELECT T01.*, T02.EMAIL
  FROM SETLIST T01
  INNER JOIN MEMBER T02 ON T01.MEMBER_ID = T02.ID
  LEFT JOIN BLACKLIST T03 
    ON T01.CHANNEL_ID = T03.CHANNEL_ID AND T03.MEMBER_ID = :memberId
  WHERE T03.CHANNEL_ID IS NULL
  ORDER BY T01.${orderType} DESC    
  OFFSET :startRow ROWS FETCH NEXT :pageSize ROWS ONLY
`;

export const GET_MAX_COUNT_WITH_WHITELIST = `
  SELECT COUNT(*)
  FROM SETLIST T01, MEMBER T02, WHITELIST T03
  WHERE T01.MEMBER_ID = T02.ID
    AND T01.CHANNEL_ID = T03.CHANNEL_ID
    AND T03.MEMBER_ID = :memberId
`;

export const GET_ALL_SETLIST_WITH_WHITELIST = (orderType: SetlistOrderType) => `
  SELECT T01.*, T02.EMAIL
  FROM SETLIST T01, MEMBER T02, WHITELIST T03
  WHERE T01.MEMBER_ID = T02.ID 
    AND T01.CHANNEL_ID = T03.CHANNEL_ID 
    AND T03.MEMBER_ID = :memberId
  ORDER BY T01.${orderType} DESC    
  OFFSET :startRow ROWS FETCH NEXT :pageSize ROWS ONLY
`;

export const SEARCH_MAX_COUNT = `
  SELECT COUNT(*)
  FROM SETLIST T01
  LEFT JOIN BLACKLIST T03 
    ON T01.CHANNEL_ID = T03.CHANNEL_ID AND T03.MEMBER_ID = :memberId
  WHERE T03.CHANNEL_ID IS NULL 
    AND LOWER(DESCRIPTION) LIKE '%' || :pattern || '%'
`;

export const SEARCH_SETLIST = (orderType: SetlistOrderType) => `
  SELECT T01.*, T02.EMAIL
  FROM SETLIST T01
  INNER JOIN MEMBER T02 ON T01.MEMBER_ID = T02.ID
  LEFT JOIN BLACKLIST T03 
    ON T01.CHANNEL_ID = T03.CHANNEL_ID AND T03.MEMBER_ID = :memberId
  WHERE T03.CHANNEL_ID IS NULL
    AND LOWER(T01.DESCRIPTION) LIKE '%' || :pattern || '%'
  ORDER BY T01.${orderType} DESC    
  OFFSET :startRow ROWS FETCH NEXT :pageSize ROWS ONLY
`;

export const SEARCH_MAX_COUNT_WITH_WHITELIST = `
  SELECT COUNT(*)
  FROM SETLIST T01, MEMBER T02, WHITELIST T03
  WHERE T01.MEMBER_ID = T02.ID
    AND T01.CHANNEL_ID = T03.CHANNEL_ID
    AND T03.MEMBER_ID = :memberId
    AND LOWER(T01.DESCRIPTION) LIKE '%' || :pattern || '%'
`;

export const SEARCH_SETLIST_WITH_WHITELIST = (orderType: SetlistOrderType) => `
  SELECT T01.*, T02.EMAIL
  FROM SETLIST T01, MEMBER T02, WHITELIST T03
  WHERE T01.MEMBER_ID = T02.ID 
    AND T01.CHANNEL_ID = T03.CHANNEL_ID 
    AND T03.MEMBER_ID = :memberId
    AND LOWER(T01.DESCRIPTION) LIKE '%' || :pattern || '%'
  ORDER BY T01.${orderType} DESC    
  OFFSET :startRow ROWS FETCH NEXT :pageSize ROWS ONLY
`;

export const POST_SETLIST = `
  INSERT INTO SETLIST (VIDEO_ID, DESCRIPTION, MEMBER_ID, CHANNEL_ID, BROADCAST_AT, TITLE)
  VALUES (:videoId, :description, :memberId, :channelId, :broadcastAt, :title)
`;

export const UPDATE_SETLIST = `
  UPDATE SETLIST
  SET 
    title = :title,
    DESCRIPTION = :description, 
    CHANNEL_ID = :channelId, 
    MEMBER_ID = :memberId, 
    UPDATE_AT = CURRENT_TIMESTAMP, 
    BROADCAST_AT = :broadcastAt 
  WHERE VIDEO_ID = :videoId
`;

export const DELETE_SETLIST = `
  DELETE FROM SETLIST
  WHERE VIDEO_ID = :videoId
`;
